### ISSUE TITLE
JWT Authentification & Autorisation

### ISSUE THREAD

**Issue by hsouf** [HamzaEzzRa/Titsuite#13]

**Comment by HamzaEzzRa** [comment]
- L'API d'authentification est presque achevée. Il me reste encore à ajouter un Refresh Token pour le JWT et une activation du compte par mail.
- L'autorisation par role (Customer, Freelancer, Staff) est prête et peut être ajoutée aux routes.

**Comment by hsouf** [comment]
Perfect

**Comment by hsouf** [comment]
Don't forget to commit the changes
