### ISSUE TITLE
Diagrammes de Séquence

### ISSUE THREAD

**Issue by HamzaEzzRa** [HamzaEzzRa/Titsuite#4]
### Goals

- Réaliser les diagrammes de séquence attribués à chaque membre.
- Se réunir pour discuter les diagrammes et organiser les tâches suivantes.

### Deadline

- Le 31/01/2021 à 16H00.

### Attachments
<br />

![Distribution des tâches](https://user-images.githubusercontent.com/55510541/106178052-94d7e700-6199-11eb-8a5b-a7d00d8f7492.jpeg)

**Comment by aminejamai** [comment]
Use Case Diagram : 

![UseCaseDiagram1](https://user-images.githubusercontent.com/40129601/107118319-85832880-6880-11eb-90bf-51354aad26c5.png)

**Comment by aminejamai** [comment]
Diagramme de séquence : Gestion des réclamations

![Gestion des reclamations](https://user-images.githubusercontent.com/40129601/107118334-af3c4f80-6880-11eb-839e-91cefd45bbd3.png)

**Comment by aminejamai** [comment]
Diagramme de séquence : Postuler sa candidature

![Postuler sa candidature](https://user-images.githubusercontent.com/40129601/107118339-bfecc580-6880-11eb-9b88-d66172617bbd.png)

**Comment by HamzaEzzRa** [comment]
Diagramme de Séquence : Authentification
<br/>
![Authentification](https://user-images.githubusercontent.com/55510541/107118511-d5aeba80-6881-11eb-925c-77e79542700b.png)

**Comment by HamzaEzzRa** [comment]
Diagrammes de Séquence : Administrateur
<br/>
![Gestion des offres](https://user-images.githubusercontent.com/55510541/107118561-0a227680-6882-11eb-89d3-7377c83347b1.png)
<br/>
![Gestion des paiements](https://user-images.githubusercontent.com/55510541/107118570-14dd0b80-6882-11eb-996b-9bf499ddad8e.png)
<br/>
![Gestion des utilisateurs](https://user-images.githubusercontent.com/55510541/107118577-1e667380-6882-11eb-8b46-b5cfadb11f6a.png)
