### ISSUE TITLE
Diagramme de Classes

### ISSUE THREAD

**Issue by HamzaEzzRa** [HamzaEzzRa/Titsuite#5]
### Goals

- Se réunir pour réaliser le diagramme de classes.
- Décider et distribuer les tâches suivantes (Maquettes, Front-end, Back-end).

### Deadline

- Le 05/02/2021 à 20H00.

**Comment by aminejamai** [comment]
file:///C:/Users/amine/Downloads/ClassDiagramJEE.png

**Comment by aminejamai** [comment]
![ClassDiagramJEE](https://user-images.githubusercontent.com/40129601/107118278-47860480-6880-11eb-9787-0f84b7c43c55.png)
